<?php
declare(strict_types=1);

require_once __DIR__ . '/../bootstrap_web.php';

use PU239\Http\Router;
use PU239\Http\MiddlewarePipeline;
use PU239\Http\Handlers\LegacyProxyHandler;
use PU239\Http\Middlewares\ForceHttps;
use PU239\Http\Middlewares\Hsts;
use PU239\Http\Middlewares\SecurityHeaders;
use PU239\Http\Middlewares\RateLimitPost;
use PU239\Http\Middlewares\CsrfGate;
use PU239\Http\Middlewares\JsonOut;
use PU239\Http\Middlewares\AuthZGate;

if (!defined('PU239_ROUTED')) {
    define('PU239_ROUTED', true);
}

$router = new Router();

$pipeline = new MiddlewarePipeline([
    new ForceHttps(),
    new Hsts(),
    new SecurityHeaders(),
    new RateLimitPost(10, 60),
    new CsrfGate(),
    new JsonOut(),
]);

// Optional legacy home mapping
$router->get('/', \PU239\Http\Handlers\HomeHandler::class, ['legacy' => __DIR__ . '/index.legacy.php']);
$router->get('/index.php', \PU239\Http\Handlers\HomeHandler::class, ['legacy' => __DIR__ . '/index.legacy.php']);

// Public routes
$router->get('/coins.php', \PU239\Http\Handlers\PublicSite\CoinsHandler::class);
$router->get('/credits.php', \PU239\Http\Handlers\PublicSite\CreditsHandler::class);
$router->get('/friends.php', \PU239\Http\Handlers\PublicSite\FriendsHandler::class);
$router->get('/gift.php', \PU239\Http\Handlers\PublicSite\GiftHandler::class);
$router->get('/invite.php', \PU239\Http\Handlers\PublicSite\InviteHandler::class);
$router->get('/messages.php', \PU239\Http\Handlers\PublicSite\MessagesHandler::class);
$router->get('/reputation.php', \PU239\Http\Handlers\PublicSite\ReputationHandler::class);
$router->get('/comment.php', \PU239\Http\Handlers\PublicSite\CommentHandler::class);
$router->get('/staffbox.php', \PU239\Http\Handlers\PublicSite\StaffboxHandler::class);
$router->get('/users.php', \PU239\Http\Handlers\PublicSite\UsersHandler::class);
$router->get('/usercp.php', \PU239\Http\Handlers\PublicSite\UsercpHandler::class);
$router->get('/usermood.php', \PU239\Http\Handlers\PublicSite\UsermoodHandler::class);
$router->get('/takeedit.php', \PU239\Http\Handlers\PublicSite\TakeeditHandler::class);
$router->get('/takeeditcp.php', \PU239\Http\Handlers\PublicSite\TakeeditcpHandler::class);
$router->get('/take_theme.php', \PU239\Http\Handlers\PublicSite\TakeThemeHandler::class);
$router->get('/takereseed.php', \PU239\Http\Handlers\PublicSite\TakereseedHandler::class);
$router->post('/takereseed.php', \PU239\Http\Handlers\PublicSite\TakereseedHandler::class);
$router->get('/takethankyou.php', \PU239\Http\Handlers\PublicSite\TakethankyouHandler::class);
$router->post('/takethankyou.php', \PU239\Http\Handlers\PublicSite\TakethankyouHandler::class);
$router->get('/takeupload.php', \PU239\Http\Handlers\PublicSite\TakeuploadHandler::class);
$router->post('/takeupload.php', \PU239\Http\Handlers\PublicSite\TakeuploadHandler::class);
$router->get('/tenpercent.php', \PU239\Http\Handlers\PublicSite\TenpercentHandler::class);
$router->post('/tenpercent.php', \PU239\Http\Handlers\PublicSite\TenpercentHandler::class);
$router->get('/tmovies.php', \PU239\Http\Handlers\PublicSite\TmoviesHandler::class);
$router->get('/topmoods.php', \PU239\Http\Handlers\PublicSite\TopmoodsHandler::class);
$router->get('/topten.php', \PU239\Http\Handlers\PublicSite\ToptenHandler::class);
$router->get('/trivia_results.php', \PU239\Http\Handlers\PublicSite\TriviaResultsHandler::class);
$router->get('/tvshows.php', \PU239\Http\Handlers\PublicSite\TvshowsHandler::class);
$router->get('/user_unlocks.php', \PU239\Http\Handlers\PublicSite\UserUnlocksHandler::class);
$router->post('/user_unlocks.php', \PU239\Http\Handlers\PublicSite\UserUnlocksHandler::class);
$router->get('/useragreement.php', \PU239\Http\Handlers\PublicSite\UseragreementHandler::class);
$router->get('/usercomment.php', \PU239\Http\Handlers\PublicSite\UsercommentHandler::class);
$router->post('/usercomment.php', \PU239\Http\Handlers\PublicSite\UsercommentHandler::class);
$router->get('/userdetails.php', \PU239\Http\Handlers\PublicSite\UserdetailsHandler::class);
$router->get('/userhistory.php', \PU239\Http\Handlers\PublicSite\UserhistoryHandler::class);
$router->get('/verify.php', \PU239\Http\Handlers\PublicSite\VerifyHandler::class);
$router->post('/verify.php', \PU239\Http\Handlers\PublicSite\VerifyHandler::class);
$router->get('/verify_email.php', \PU239\Http\Handlers\PublicSite\VerifyEmailHandler::class);
$router->get('/videoformats.php', \PU239\Http\Handlers\PublicSite\VideoformatsHandler::class);
$router->get('/view_announce_history.php', \PU239\Http\Handlers\PublicSite\ViewAnnounceHistoryHandler::class);
$router->get('/view_sql.php', \PU239\Http\Handlers\PublicSite\ViewSqlHandler::class);
$router->get('/viewnfo.php', \PU239\Http\Handlers\PublicSite\ViewnfoHandler::class);
$router->get('/wiki.php', \PU239\Http\Handlers\PublicSite\WikiHandler::class);
$router->post('/wiki.php', \PU239\Http\Handlers\PublicSite\WikiHandler::class);
$router->get('/achievementbonus.php', \PU239\Http\Handlers\PublicSite\AchievementbonusHandler::class);
$router->get('/achievementhistory.php', \PU239\Http\Handlers\PublicSite\AchievementhistoryHandler::class);
$router->get('/achievementlist.php', \PU239\Http\Handlers\PublicSite\AchievementlistHandler::class);
$router->post('/achievementlist.php', \PU239\Http\Handlers\PublicSite\AchievementlistHandler::class);
$router->get('/ajaxchat.php', \PU239\Http\Handlers\PublicSite\AjaxchatHandler::class);
$router->get('/allsmiles.php', \PU239\Http\Handlers\PublicSite\AllsmilesHandler::class);
$router->get('/anatomy.php', \PU239\Http\Handlers\PublicSite\AnatomyHandler::class);
$router->get('/announcement.php', \PU239\Http\Handlers\PublicSite\AnnouncementHandler::class);
$router->get('/arcade.php', \PU239\Http\Handlers\PublicSite\ArcadeHandler::class);
$router->get('/arcade_top_scores.php', \PU239\Http\Handlers\PublicSite\ArcadeTopScoresHandler::class);
$router->get('/bitbucket.php', \PU239\Http\Handlers\PublicSite\BitbucketHandler::class);
$router->get('/bjstats.php', \PU239\Http\Handlers\PublicSite\BjstatsHandler::class);
$router->get('/blackjack.php', \PU239\Http\Handlers\PublicSite\BlackjackHandler::class);
$router->get('/bookmarks.php', \PU239\Http\Handlers\PublicSite\BookmarksHandler::class);
$router->get('/bot_triggers.php', \PU239\Http\Handlers\PublicSite\BotTriggersHandler::class);
$router->get('/browse.php', \PU239\Http\Handlers\PublicSite\BrowseHandler::class);
$router->get('/bugs.php', \PU239\Http\Handlers\PublicSite\BugsHandler::class);
$router->post('/bugs.php', \PU239\Http\Handlers\PublicSite\BugsHandler::class);
$router->get('/casino.php', \PU239\Http\Handlers\PublicSite\CasinoHandler::class);
$router->get('/catalog.php', \PU239\Http\Handlers\PublicSite\CatalogHandler::class);
$router->get('/categoryids.php', \PU239\Http\Handlers\PublicSite\CategoryidsHandler::class);
$router->get('/chat.php', \PU239\Http\Handlers\PublicSite\ChatHandler::class);
$router->get('/clear_announcement.php', \PU239\Http\Handlers\PublicSite\ClearAnnouncementHandler::class);
$router->get('/contactstaff.php', \PU239\Http\Handlers\PublicSite\ContactstaffHandler::class);
$router->post('/contactstaff.php', \PU239\Http\Handlers\PublicSite\ContactstaffHandler::class);
$router->get('/delete.php', \PU239\Http\Handlers\PublicSite\DeleteHandler::class);
$router->post('/delete.php', \PU239\Http\Handlers\PublicSite\DeleteHandler::class);
$router->get('/details.php', \PU239\Http\Handlers\PublicSite\DetailsHandler::class);
$router->post('/details.php', \PU239\Http\Handlers\PublicSite\DetailsHandler::class);
$router->get('/download.php', \PU239\Http\Handlers\PublicSite\DownloadHandler::class);
$router->get('/download_multi.php', \PU239\Http\Handlers\PublicSite\DownloadMultiHandler::class);
$router->get('/downloadsub.php', \PU239\Http\Handlers\PublicSite\DownloadsubHandler::class);
$router->post('/downloadsub.php', \PU239\Http\Handlers\PublicSite\DownloadsubHandler::class);
$router->get('/edit.php', \PU239\Http\Handlers\PublicSite\EditHandler::class);
$router->post('/edit.php', \PU239\Http\Handlers\PublicSite\EditHandler::class);
$router->get('/faq.php', \PU239\Http\Handlers\PublicSite\FaqHandler::class);
$router->get('/fastdelete.php', \PU239\Http\Handlers\PublicSite\FastdeleteHandler::class);
$router->get('/filelist.php', \PU239\Http\Handlers\PublicSite\FilelistHandler::class);
$router->get('/flash.php', \PU239\Http\Handlers\PublicSite\FlashHandler::class);
$router->get('/forums.php', \PU239\Http\Handlers\PublicSite\ForumsHandler::class);
$router->get('/games.php', \PU239\Http\Handlers\PublicSite\GamesHandler::class);
$router->get('/getrss.php', \PU239\Http\Handlers\PublicSite\GetrssHandler::class);
$router->get('/happylog.php', \PU239\Http\Handlers\PublicSite\HappylogHandler::class);
$router->get('/hnrs.php', \PU239\Http\Handlers\PublicSite\HnrsHandler::class);
$router->get('/img.php', \PU239\Http\Handlers\PublicSite\ImgHandler::class);
$router->get('/login.php', \PU239\Http\Handlers\PublicSite\LoginHandler::class);
$router->post('/login.php', \PU239\Http\Handlers\PublicSite\LoginHandler::class);
$router->get('/logout.php', \PU239\Http\Handlers\PublicSite\LogoutHandler::class);
$router->get('/lottery.php', \PU239\Http\Handlers\PublicSite\LotteryHandler::class);
$router->get('/movies.php', \PU239\Http\Handlers\PublicSite\MoviesHandler::class);
$router->get('/mybonus.php', \PU239\Http\Handlers\PublicSite\MybonusHandler::class);
$router->post('/mybonus.php', \PU239\Http\Handlers\PublicSite\MybonusHandler::class);
$router->get('/mytorrents.php', \PU239\Http\Handlers\PublicSite\MytorrentsHandler::class);
$router->get('/needseed.php', \PU239\Http\Handlers\PublicSite\NeedseedHandler::class);
$router->get('/new_announcement.php', \PU239\Http\Handlers\PublicSite\NewAnnouncementHandler::class);
$router->post('/new_announcement.php', \PU239\Http\Handlers\PublicSite\NewAnnouncementHandler::class);
$router->get('/offers.php', \PU239\Http\Handlers\PublicSite\OffersHandler::class);
$router->post('/offers.php', \PU239\Http\Handlers\PublicSite\OffersHandler::class);
$router->get('/peerlist.php', \PU239\Http\Handlers\PublicSite\PeerlistHandler::class);
$router->get('/polls_take_vote.php', \PU239\Http\Handlers\PublicSite\PollsTakeVoteHandler::class);
$router->post('/polls_take_vote.php', \PU239\Http\Handlers\PublicSite\PollsTakeVoteHandler::class);
$router->get('/port_check.php', \PU239\Http\Handlers\PublicSite\PortCheckHandler::class);
$router->get('/recover.php', \PU239\Http\Handlers\PublicSite\RecoverHandler::class);
$router->post('/recover.php', \PU239\Http\Handlers\PublicSite\RecoverHandler::class);
$router->get('/report.php', \PU239\Http\Handlers\PublicSite\ReportHandler::class);
$router->post('/report.php', \PU239\Http\Handlers\PublicSite\ReportHandler::class);
$router->get('/requests.php', \PU239\Http\Handlers\PublicSite\RequestsHandler::class);
$router->post('/requests.php', \PU239\Http\Handlers\PublicSite\RequestsHandler::class);
$router->get('/restoreclass.php', \PU239\Http\Handlers\PublicSite\RestoreclassHandler::class);
$router->get('/rss.php', \PU239\Http\Handlers\PublicSite\RssHandler::class);
$router->get('/rss_pdo_demo.php', \PU239\Http\Handlers\PublicSite\RssPdoDemoHandler::class);
$router->get('/rsstfreak.php', \PU239\Http\Handlers\PublicSite\RsstfreakHandler::class);
$router->get('/rules.php', \PU239\Http\Handlers\PublicSite\RulesHandler::class);

$router->get('/admin/acpmanage.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/acpmanage.php']);
$router->post('/admin/acpmanage.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/acpmanage.php']);
$router->get('/admin/adduser.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/adduser.php']);
$router->post('/admin/adduser.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/adduser.php']);
$router->get('/admin/backup.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/backup.php']);
$router->post('/admin/backup.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/backup.php']);
$router->get('/admin/bannedemails.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/bannedemails.php']);
$router->post('/admin/bannedemails.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/bannedemails.php']);
$router->get('/admin/bans.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/bans.php']);
$router->post('/admin/bans.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/bans.php']);
$router->get('/admin/block.settings.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/block.settings.php']);
$router->post('/admin/block.settings.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/block.settings.php']);
$router->get('/admin/bonusmanage.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/bonusmanage.php']);
$router->post('/admin/bonusmanage.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/bonusmanage.php']);
$router->get('/admin/categories.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/categories.php']);
$router->post('/admin/categories.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/categories.php']);
$router->get('/admin/cheaters.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/cheaters.php']);
$router->post('/admin/cheaters.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/cheaters.php']);
$router->get('/admin/class_config.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/class_config.php']);
$router->post('/admin/class_config.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/class_config.php']);
$router->get('/admin/cleanup_manager.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/cleanup_manager.php']);
$router->post('/admin/cleanup_manager.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/cleanup_manager.php']);
$router->get('/admin/cloudview.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/cloudview.php']);
$router->post('/admin/cloudview.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/cloudview.php']);
$router->get('/admin/datareset.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/datareset.php']);
$router->post('/admin/datareset.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/datareset.php']);
$router->get('/admin/deathrow.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/deathrow.php']);
$router->post('/admin/deathrow.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/deathrow.php']);
$router->get('/admin/delacct.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/delacct.php']);
$router->post('/admin/delacct.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/delacct.php']);
$router->get('/admin/edit_moods.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/edit_moods.php']);
$router->post('/admin/edit_moods.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/edit_moods.php']);
$router->get('/admin/editlog.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/editlog.php']);
$router->post('/admin/editlog.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/editlog.php']);
$router->get('/admin/findnotconnectable.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/findnotconnectable.php']);
$router->post('/admin/findnotconnectable.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/findnotconnectable.php']);
$router->get('/admin/floodlimit.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/floodlimit.php']);
$router->post('/admin/floodlimit.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/floodlimit.php']);
$router->get('/admin/forum_config.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/forum_config.php']);
$router->post('/admin/forum_config.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/forum_config.php']);
$router->get('/admin/forum_manage.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/forum_manage.php']);
$router->post('/admin/forum_manage.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/forum_manage.php']);
$router->get('/admin/freeleech.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/freeleech.php']);
$router->post('/admin/freeleech.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/freeleech.php']);
$router->get('/admin/grouppm.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/grouppm.php']);
$router->post('/admin/grouppm.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/grouppm.php']);
$router->get('/admin/hit_and_run_settings.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/hit_and_run_settings.php']);
$router->post('/admin/hit_and_run_settings.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/hit_and_run_settings.php']);
$router->get('/admin/hnrwarn.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/hnrwarn.php']);
$router->post('/admin/hnrwarn.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/hnrwarn.php']);
$router->get('/admin/inactive.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/inactive.php']);
$router->post('/admin/inactive.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/inactive.php']);
$router->get('/admin/invite_tree.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/invite_tree.php']);
$router->post('/admin/invite_tree.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/invite_tree.php']);
$router->get('/admin/leechwarn.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/leechwarn.php']);
$router->post('/admin/leechwarn.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/leechwarn.php']);
$router->get('/admin/log_viewer.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/log_viewer.php']);
$router->post('/admin/log_viewer.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/log_viewer.php']);
$router->get('/admin/manage_images.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/manage_images.php']);
$router->post('/admin/manage_images.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/manage_images.php']);
$router->get('/admin/mass_bonus_for_members.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/mass_bonus_for_members.php']);
$router->post('/admin/mass_bonus_for_members.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/mass_bonus_for_members.php']);
$router->get('/admin/mega_search.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/mega_search.php']);
$router->post('/admin/mega_search.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/mega_search.php']);
$router->get('/admin/modded_torrents.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/modded_torrents.php']);
$router->post('/admin/modded_torrents.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/modded_torrents.php']);
$router->get('/admin/modtask.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/modtask.php']);
$router->post('/admin/modtask.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/modtask.php']);
$router->get('/admin/news.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/news.php']);
$router->post('/admin/news.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/news.php']);
$router->get('/admin/over_forums.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/over_forums.php']);
$router->post('/admin/over_forums.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/over_forums.php']);
$router->get('/admin/polls_manager.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/polls_manager.php']);
$router->post('/admin/polls_manager.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/polls_manager.php']);
$router->get('/admin/promo.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/promo.php']);
$router->post('/admin/promo.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/promo.php']);
$router->get('/admin/reputation_settings.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/reputation_settings.php']);
$router->post('/admin/reputation_settings.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/reputation_settings.php']);
$router->get('/admin/reset.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/reset.php']);
$router->post('/admin/reset.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/reset.php']);
$router->get('/admin/site_settings.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/site_settings.php']);
$router->post('/admin/site_settings.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/site_settings.php']);
$router->get('/admin/sysoplog.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/sysoplog.php']);
$router->post('/admin/sysoplog.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/sysoplog.php']);
$router->get('/admin/themes.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/themes.php']);
$router->post('/admin/themes.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/themes.php']);
$router->get('/admin/traceroute.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/traceroute.php']);
$router->post('/admin/traceroute.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/traceroute.php']);
$router->get('/admin/trivia_config.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/trivia_config.php']);
$router->post('/admin/trivia_config.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/trivia_config.php']);
$router->get('/admin/upgrade_database.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/upgrade_database.php']);
$router->post('/admin/upgrade_database.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/upgrade_database.php']);
$router->get('/admin/uploadapps.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/uploadapps.php']);
$router->post('/admin/uploadapps.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/uploadapps.php']);
$router->get('/admin/usersearch.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/usersearch.php']);
$router->post('/admin/usersearch.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/usersearch.php']);
$router->get('/admin/watched_users.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/watched_users.php']);
$router->post('/admin/watched_users.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/../admin/watched_users.php']);
$router->get('/ajax/autocomplete.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/autocomplete.php']);
$router->post('/ajax/autocomplete.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/autocomplete.php']);
$router->get('/ajax/bookmarks.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/bookmarks.php']);
$router->post('/ajax/bookmarks.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/bookmarks.php']);
$router->get('/ajax/checkport.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/checkport.php']);
$router->post('/ajax/checkport.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/checkport.php']);
$router->get('/ajax/checkports.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/checkports.php']);
$router->post('/ajax/checkports.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/checkports.php']);
$router->get('/ajax/cooker_notify.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/cooker_notify.php']);
$router->post('/ajax/cooker_notify.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/cooker_notify.php']);
$router->get('/ajax/descr_format.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/descr_format.php']);
$router->post('/ajax/descr_format.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/descr_format.php']);
$router->get('/ajax/ebook_lookup.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/ebook_lookup.php']);
$router->post('/ajax/ebook_lookup.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/ebook_lookup.php']);
$router->get('/ajax/imdb_lookup.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/imdb_lookup.php']);
$router->post('/ajax/imdb_lookup.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/imdb_lookup.php']);
$router->get('/ajax/isbn_lookup.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/isbn_lookup.php']);
$router->post('/ajax/isbn_lookup.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/isbn_lookup.php']);
$router->get('/ajax/like.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/like.php']);
$router->post('/ajax/like.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/like.php']);
$router->get('/ajax/member_input.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/member_input.php']);
$router->post('/ajax/member_input.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/member_input.php']);
$router->get('/ajax/offer_notify.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/offer_notify.php']);
$router->post('/ajax/offer_notify.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/offer_notify.php']);
$router->get('/ajax/offer_status.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/offer_status.php']);
$router->post('/ajax/offer_status.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/offer_status.php']);
$router->get('/ajax/offer_vote.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/offer_vote.php']);
$router->post('/ajax/offer_vote.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/offer_vote.php']);
$router->get('/ajax/rating.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/rating.php']);
$router->post('/ajax/rating.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/rating.php']);
$router->get('/ajax/request_notify.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/request_notify.php']);
$router->post('/ajax/request_notify.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/request_notify.php']);
$router->get('/ajax/request_vote.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/request_vote.php']);
$router->post('/ajax/request_vote.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/request_vote.php']);
$router->get('/ajax/show_in_navbar.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/show_in_navbar.php']);
$router->post('/ajax/show_in_navbar.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/show_in_navbar.php']);
$router->get('/ajax/staff_picks.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/staff_picks.php']);
$router->post('/ajax/staff_picks.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/staff_picks.php']);
$router->get('/ajax/take_upload.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/take_upload.php']);
$router->post('/ajax/take_upload.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/take_upload.php']);
$router->get('/ajax/take_url_upload.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/take_url_upload.php']);
$router->post('/ajax/take_url_upload.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/take_url_upload.php']);
$router->get('/ajax/thanks.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/thanks.php']);
$router->post('/ajax/thanks.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/thanks.php']);
$router->get('/ajax/torrents_lookup.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/torrents_lookup.php']);
$router->post('/ajax/torrents_lookup.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/torrents_lookup.php']);
$router->get('/ajax/trivia_answers.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/trivia_answers.php']);
$router->post('/ajax/trivia_answers.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/trivia_answers.php']);
$router->get('/ajax/tvmaze_lookup.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/tvmaze_lookup.php']);
$router->post('/ajax/tvmaze_lookup.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/tvmaze_lookup.php']);
$router->get('/ajax/usersearch.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/usersearch.php']);
$router->post('/ajax/usersearch.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/ajax/usersearch.php']);
$router->get('/index.legacy.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/index.legacy.php']);
$router->post('/index.legacy.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/index.legacy.php']);
$router->get('/search.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/search.php']);
$router->post('/search.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/search.php']);
$router->get('/signup.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/signup.php']);
$router->post('/signup.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/signup.php']);
$router->get('/subtitles.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/subtitles.php']);
$router->post('/subtitles.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/subtitles.php']);
$router->get('/tags.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/tags.php']);
$router->post('/tags.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/tags.php']);
$router->get('/upcoming.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/upcoming.php']);
$router->post('/upcoming.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/upcoming.php']);
$router->get('/uploadapp.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/uploadapp.php']);
$router->post('/uploadapp.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/uploadapp.php']);
$router->get('/user_blocks.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/user_blocks.php']);
$router->post('/user_blocks.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/user_blocks.php']);

// Legacy HTTP front controller marker

// Admin/staff (with AuthZGate metadata)
$router->get('/admin/namechanger.php', \PU239\Http\Handlers\Admin\NamechangerHandler::class, ['authz' => new AuthZGate('admin')]);
$router->get('/admin/reports.php', \PU239\Http\Handlers\Admin\ReportsHandler::class, ['authz' => new AuthZGate('admin')]);
$router->get('/admin/warn.php', \PU239\Http\Handlers\Admin\WarnHandler::class, ['authz' => new AuthZGate('admin')]);
$router->get('/admin/class_promo.php', \PU239\Http\Handlers\Admin\ClassPromoHandler::class, ['authz' => new AuthZGate('admin')]);
$router->get('/admin/sitelog.php', \PU239\Http\Handlers\Admin\SitelogHandler::class, ['authz' => new AuthZGate('admin')]);
$router->get('/admin/comments.php', \PU239\Http\Handlers\Admin\CommentsHandler::class, ['authz' => new AuthZGate('admin')]);
$router->get('/admin/reputation_ad.php', \PU239\Http\Handlers\Admin\ReputationAdHandler::class, ['authz' => new AuthZGate('admin')]);
$router->get('/admin/shit_list.php', \PU239\Http\Handlers\Admin\ShitListHandler::class, ['authz' => new AuthZGate('admin')]);
$router->get('/admin/system_view.php', \PU239\Http\Handlers\Admin\SystemViewHandler::class, ['authz' => new AuthZGate('admin')]);

$router->get('/staffpanel.php', \PU239\Http\Handlers\Staffpanel\IndexHandler::class, ['authz' => new AuthZGate(['any' => ['staff', 'admin']])]);
$router->get('/staffpanel/index.php', \PU239\Http\Handlers\Staffpanel\IndexHandler::class, ['authz' => new AuthZGate(['any' => ['staff', ' admin']])]);

$pipeline->handle($router);

// Legacy HTTP front controller marker
