<?php
declare(strict_types=1);

require_once __DIR__ . '/../bootstrap_web.php';

use PU239\Http\Router;
use PU239\Http\MiddlewarePipeline;
use PU239\Http\Handlers\LegacyProxyHandler;
use PU239\Http\Middlewares\ForceHttps;
use PU239\Http\Middlewares\Hsts;
use PU239\Http\Middlewares\SecurityHeaders;
use PU239\Http\Middlewares\RateLimitPost;
use PU239\Http\Middlewares\CsrfGate;
use PU239\Http\Middlewares\JsonOut;
use PU239\Http\Middlewares\AuthZGate;

if (!defined('PU239_ROUTED')) {
    define('PU239_ROUTED', true);
}

$router = new Router();

$pipeline = new MiddlewarePipeline([
    new ForceHttps(),
    new Hsts(),
    new SecurityHeaders(),
    new RateLimitPost(10, 60),
    new CsrfGate(),
    new JsonOut(),
]);

// Optional legacy home mapping
$router->get('/', \PU239\Http\Handlers\HomeHandler::class, ['legacy' => __DIR__ . '/index.legacy.php']);
$router->get('/index.php', \PU239\Http\Handlers\HomeHandler::class, ['legacy' => __DIR__ . '/index.legacy.php']);

// Public routes
$router->get('/coins.php', \PU239\Http\Handlers\PublicSite\CoinsHandler::class);
$router->get('/credits.php', \PU239\Http\Handlers\PublicSite\CreditsHandler::class);
$router->get('/friends.php', \PU239\Http\Handlers\PublicSite\FriendsHandler::class);
$router->get('/gift.php', \PU239\Http\Handlers\PublicSite\GiftHandler::class);
$router->get('/invite.php', \PU239\Http\Handlers\PublicSite\InviteHandler::class);
$router->get('/messages.php', \PU239\Http\Handlers\PublicSite\MessagesHandler::class);
$router->get('/reputation.php', \PU239\Http\Handlers\PublicSite\ReputationHandler::class);
$router->get('/comment.php', \PU239\Http\Handlers\PublicSite\CommentHandler::class);
$router->get('/staffbox.php', \PU239\Http\Handlers\PublicSite\StaffboxHandler::class);
$router->get('/users.php', \PU239\Http\Handlers\PublicSite\UsersHandler::class);
$router->get('/usercp.php', \PU239\Http\Handlers\PublicSite\UsercpHandler::class);
$router->get('/usermood.php', \PU239\Http\Handlers\PublicSite\UsermoodHandler::class);
$router->get('/takeedit.php', \PU239\Http\Handlers\PublicSite\TakeeditHandler::class);
$router->get('/takeeditcp.php', \PU239\Http\Handlers\PublicSite\TakeeditcpHandler::class);
$router->get('/take_theme.php', \PU239\Http\Handlers\PublicSite\TakeThemeHandler::class);
$router->get('/takereseed.php', \PU239\Http\Handlers\PublicSite\TakereseedHandler::class);
$router->post('/takereseed.php', \PU239\Http\Handlers\PublicSite\TakereseedHandler::class);
$router->get('/takethankyou.php', \PU239\Http\Handlers\PublicSite\TakethankyouHandler::class);
$router->post('/takethankyou.php', \PU239\Http\Handlers\PublicSite\TakethankyouHandler::class);
$router->get('/takeupload.php', \PU239\Http\Handlers\PublicSite\TakeuploadHandler::class);
$router->post('/takeupload.php', \PU239\Http\Handlers\PublicSite\TakeuploadHandler::class);
$router->get('/tenpercent.php', \PU239\Http\Handlers\PublicSite\TenpercentHandler::class);
$router->post('/tenpercent.php', \PU239\Http\Handlers\PublicSite\TenpercentHandler::class);
$router->get('/tmovies.php', \PU239\Http\Handlers\PublicSite\TmoviesHandler::class);
$router->get('/topmoods.php', \PU239\Http\Handlers\PublicSite\TopmoodsHandler::class);
$router->get('/topten.php', \PU239\Http\Handlers\PublicSite\ToptenHandler::class);
$router->get('/trivia_results.php', \PU239\Http\Handlers\PublicSite\TriviaResultsHandler::class);
$router->get('/tvshows.php', \PU239\Http\Handlers\PublicSite\TvshowsHandler::class);
$router->get('/user_unlocks.php', \PU239\Http\Handlers\PublicSite\UserUnlocksHandler::class);
$router->post('/user_unlocks.php', \PU239\Http\Handlers\PublicSite\UserUnlocksHandler::class);
$router->get('/useragreement.php', \PU239\Http\Handlers\PublicSite\UseragreementHandler::class);
$router->get('/usercomment.php', \PU239\Http\Handlers\PublicSite\UsercommentHandler::class);
$router->post('/usercomment.php', \PU239\Http\Handlers\PublicSite\UsercommentHandler::class);
$router->get('/userdetails.php', \PU239\Http\Handlers\PublicSite\UserdetailsHandler::class);
$router->get('/userhistory.php', \PU239\Http\Handlers\PublicSite\UserhistoryHandler::class);
$router->get('/verify.php', \PU239\Http\Handlers\PublicSite\VerifyHandler::class);
$router->post('/verify.php', \PU239\Http\Handlers\PublicSite\VerifyHandler::class);
$router->get('/verify_email.php', \PU239\Http\Handlers\PublicSite\VerifyEmailHandler::class);
$router->get('/videoformats.php', \PU239\Http\Handlers\PublicSite\VideoformatsHandler::class);
$router->get('/view_announce_history.php', \PU239\Http\Handlers\PublicSite\ViewAnnounceHistoryHandler::class);
$router->get('/view_sql.php', \PU239\Http\Handlers\PublicSite\ViewSqlHandler::class);
$router->get('/viewnfo.php', \PU239\Http\Handlers\PublicSite\ViewnfoHandler::class);
$router->get('/wiki.php', \PU239\Http\Handlers\PublicSite\WikiHandler::class);
$router->post('/wiki.php', \PU239\Http\Handlers\PublicSite\WikiHandler::class);
$router->get('/achievementbonus.php', \PU239\Http\Handlers\PublicSite\AchievementbonusHandler::class);
$router->get('/achievementhistory.php', \PU239\Http\Handlers\PublicSite\AchievementhistoryHandler::class);
$router->get('/achievementlist.php', \PU239\Http\Handlers\PublicSite\AchievementlistHandler::class);
$router->post('/achievementlist.php', \PU239\Http\Handlers\PublicSite\AchievementlistHandler::class);
$router->get('/ajaxchat.php', \PU239\Http\Handlers\PublicSite\AjaxchatHandler::class);
$router->get('/allsmiles.php', \PU239\Http\Handlers\PublicSite\AllsmilesHandler::class);
$router->get('/anatomy.php', \PU239\Http\Handlers\PublicSite\AnatomyHandler::class);
$router->get('/announcement.php', \PU239\Http\Handlers\PublicSite\AnnouncementHandler::class);
$router->get('/arcade.php', \PU239\Http\Handlers\PublicSite\ArcadeHandler::class);
$router->get('/arcade_top_scores.php', \PU239\Http\Handlers\PublicSite\ArcadeTopScoresHandler::class);
$router->get('/bitbucket.php', \PU239\Http\Handlers\PublicSite\BitbucketHandler::class);
$router->get('/bjstats.php', \PU239\Http\Handlers\PublicSite\BjstatsHandler::class);
$router->get('/blackjack.php', \PU239\Http\Handlers\PublicSite\BlackjackHandler::class);
$router->get('/bookmarks.php', \PU239\Http\Handlers\PublicSite\BookmarksHandler::class);
$router->get('/bot_triggers.php', \PU239\Http\Handlers\PublicSite\BotTriggersHandler::class);
$router->get('/browse.php', \PU239\Http\Handlers\PublicSite\BrowseHandler::class);
$router->get('/bugs.php', \PU239\Http\Handlers\PublicSite\BugsHandler::class);
$router->post('/bugs.php', \PU239\Http\Handlers\PublicSite\BugsHandler::class);
$router->get('/casino.php', \PU239\Http\Handlers\PublicSite\CasinoHandler::class);
$router->get('/catalog.php', \PU239\Http\Handlers\PublicSite\CatalogHandler::class);
$router->get('/categoryids.php', \PU239\Http\Handlers\PublicSite\CategoryidsHandler::class);
$router->get('/chat.php', \PU239\Http\Handlers\PublicSite\ChatHandler::class);
$router->get('/clear_announcement.php', \PU239\Http\Handlers\PublicSite\ClearAnnouncementHandler::class);
$router->get('/contactstaff.php', \PU239\Http\Handlers\PublicSite\ContactstaffHandler::class);
$router->post('/contactstaff.php', \PU239\Http\Handlers\PublicSite\ContactstaffHandler::class);
$router->get('/delete.php', \PU239\Http\Handlers\PublicSite\DeleteHandler::class);
$router->post('/delete.php', \PU239\Http\Handlers\PublicSite\DeleteHandler::class);
$router->get('/details.php', \PU239\Http\Handlers\PublicSite\DetailsHandler::class);
$router->post('/details.php', \PU239\Http\Handlers\PublicSite\DetailsHandler::class);
$router->get('/download.php', \PU239\Http\Handlers\PublicSite\DownloadHandler::class);
$router->get('/download_multi.php', \PU239\Http\Handlers\PublicSite\DownloadMultiHandler::class);
$router->get('/downloadsub.php', \PU239\Http\Handlers\PublicSite\DownloadsubHandler::class);
$router->post('/downloadsub.php', \PU239\Http\Handlers\PublicSite\DownloadsubHandler::class);
$router->get('/edit.php', \PU239\Http\Handlers\PublicSite\EditHandler::class);
$router->post('/edit.php', \PU239\Http\Handlers\PublicSite\EditHandler::class);
$router->get('/faq.php', \PU239\Http\Handlers\PublicSite\FaqHandler::class);
$router->get('/fastdelete.php', \PU239\Http\Handlers\PublicSite\FastdeleteHandler::class);
$router->get('/filelist.php', \PU239\Http\Handlers\PublicSite\FilelistHandler::class);
$router->get('/flash.php', \PU239\Http\Handlers\PublicSite\FlashHandler::class);
$router->get('/forums.php', \PU239\Http\Handlers\PublicSite\ForumsHandler::class);
$router->get('/games.php', \PU239\Http\Handlers\PublicSite\GamesHandler::class);
$router->get('/getrss.php', \PU239\Http\Handlers\PublicSite\GetrssHandler::class);
$router->get('/happylog.php', \PU239\Http\Handlers\PublicSite\HappylogHandler::class);
$router->get('/hnrs.php', \PU239\Http\Handlers\PublicSite\HnrsHandler::class);
$router->get('/img.php', \PU239\Http\Handlers\PublicSite\ImgHandler::class);
$router->get('/login.php', \PU239\Http\Handlers\PublicSite\LoginHandler::class);
$router->post('/login.php', \PU239\Http\Handlers\PublicSite\LoginHandler::class);
$router->get('/logout.php', \PU239\Http\Handlers\PublicSite\LogoutHandler::class);
$router->get('/lottery.php', \PU239\Http\Handlers\PublicSite\LotteryHandler::class);
$router->get('/movies.php', \PU239\Http\Handlers\PublicSite\MoviesHandler::class);
$router->get('/mybonus.php', \PU239\Http\Handlers\PublicSite\MybonusHandler::class);
$router->post('/mybonus.php', \PU239\Http\Handlers\PublicSite\MybonusHandler::class);
$router->get('/mytorrents.php', \PU239\Http\Handlers\PublicSite\MytorrentsHandler::class);
$router->get('/needseed.php', \PU239\Http\Handlers\PublicSite\NeedseedHandler::class);
$router->get('/new_announcement.php', \PU239\Http\Handlers\PublicSite\NewAnnouncementHandler::class);
$router->post('/new_announcement.php', \PU239\Http\Handlers\PublicSite\NewAnnouncementHandler::class);
$router->get('/offers.php', \PU239\Http\Handlers\PublicSite\OffersHandler::class);
$router->post('/offers.php', \PU239\Http\Handlers\PublicSite\OffersHandler::class);
$router->get('/peerlist.php', \PU239\Http\Handlers\PublicSite\PeerlistHandler::class);
$router->get('/polls_take_vote.php', \PU239\Http\Handlers\PublicSite\PollsTakeVoteHandler::class);
$router->post('/polls_take_vote.php', \PU239\Http\Handlers\PublicSite\PollsTakeVoteHandler::class);
$router->get('/port_check.php', \PU239\Http\Handlers\PublicSite\PortCheckHandler::class);
$router->get('/recover.php', \PU239\Http\Handlers\PublicSite\RecoverHandler::class);
$router->post('/recover.php', \PU239\Http\Handlers\PublicSite\RecoverHandler::class);
$router->get('/report.php', \PU239\Http\Handlers\PublicSite\ReportHandler::class);
$router->post('/report.php', \PU239\Http\Handlers\PublicSite\ReportHandler::class);
$router->get('/requests.php', \PU239\Http\Handlers\PublicSite\RequestsHandler::class);
$router->post('/requests.php', \PU239\Http\Handlers\PublicSite\RequestsHandler::class);
$router->get('/restoreclass.php', \PU239\Http\Handlers\PublicSite\RestoreclassHandler::class);
$router->get('/rss.php', \PU239\Http\Handlers\PublicSite\RssHandler::class);
$router->get('/rss_pdo_demo.php', \PU239\Http\Handlers\PublicSite\RssPdoDemoHandler::class);
$router->get('/rsstfreak.php', \PU239\Http\Handlers\PublicSite\RsstfreakHandler::class);
$router->get('/rules.php', \PU239\Http\Handlers\PublicSite\RulesHandler::class);

$router->get('/admin/acpmanage.php', \PU239\Http\Handlers\Admin\AcpmanageHandler::class);
$router->post('/admin/acpmanage.php', \PU239\Http\Handlers\Admin\AcpmanageHandler::class);
$router->get('/admin/adduser.php', \PU239\Http\Handlers\Admin\AdduserHandler::class);
$router->post('/admin/adduser.php', \PU239\Http\Handlers\Admin\AdduserHandler::class);
$router->get('/admin/backup.php', \PU239\Http\Handlers\Admin\BackupHandler::class);
$router->post('/admin/backup.php', \PU239\Http\Handlers\Admin\BackupHandler::class);
$router->get('/admin/bannedemails.php', \PU239\Http\Handlers\Admin\BannedemailsHandler::class);
$router->post('/admin/bannedemails.php', \PU239\Http\Handlers\Admin\BannedemailsHandler::class);
$router->get('/admin/bans.php', \PU239\Http\Handlers\Admin\BansHandler::class);
$router->post('/admin/bans.php', \PU239\Http\Handlers\Admin\BansHandler::class);
$router->get('/admin/block.settings.php', \PU239\Http\Handlers\Admin\BlockSettingsHandler::class);
$router->post('/admin/block.settings.php', \PU239\Http\Handlers\Admin\BlockSettingsHandler::class);
$router->get('/admin/bonusmanage.php', \PU239\Http\Handlers\Admin\BonusmanageHandler::class);
$router->post('/admin/bonusmanage.php', \PU239\Http\Handlers\Admin\BonusmanageHandler::class);
$router->get('/admin/categories.php', \PU239\Http\Handlers\Admin\CategoriesHandler::class);
$router->post('/admin/categories.php', \PU239\Http\Handlers\Admin\CategoriesHandler::class);
$router->get('/admin/cheaters.php', \PU239\Http\Handlers\Admin\CheatersHandler::class);
$router->post('/admin/cheaters.php', \PU239\Http\Handlers\Admin\CheatersHandler::class);
$router->get('/admin/class_config.php', \PU239\Http\Handlers\Admin\ClassConfigHandler::class);
$router->post('/admin/class_config.php', \PU239\Http\Handlers\Admin\ClassConfigHandler::class);
$router->get('/admin/cleanup_manager.php', \PU239\Http\Handlers\Admin\CleanupManagerHandler::class);
$router->post('/admin/cleanup_manager.php', \PU239\Http\Handlers\Admin\CleanupManagerHandler::class);
$router->get('/admin/cloudview.php', \PU239\Http\Handlers\Admin\CloudviewHandler::class);
$router->post('/admin/cloudview.php', \PU239\Http\Handlers\Admin\CloudviewHandler::class);
$router->get('/admin/datareset.php', \PU239\Http\Handlers\Admin\DataresetHandler::class);
$router->post('/admin/datareset.php', \PU239\Http\Handlers\Admin\DataresetHandler::class);
$router->get('/admin/deathrow.php', \PU239\Http\Handlers\Admin\DeathrowHandler::class);
$router->post('/admin/deathrow.php', \PU239\Http\Handlers\Admin\DeathrowHandler::class);
$router->get('/admin/delacct.php', \PU239\Http\Handlers\Admin\DelacctHandler::class);
$router->post('/admin/delacct.php', \PU239\Http\Handlers\Admin\DelacctHandler::class);
$router->get('/admin/edit_moods.php', \PU239\Http\Handlers\Admin\EditMoodsHandler::class);
$router->post('/admin/edit_moods.php', \PU239\Http\Handlers\Admin\EditMoodsHandler::class);
$router->get('/admin/editlog.php', \PU239\Http\Handlers\Admin\EditlogHandler::class);
$router->post('/admin/editlog.php', \PU239\Http\Handlers\Admin\EditlogHandler::class);
$router->get('/admin/findnotconnectable.php', \PU239\Http\Handlers\Admin\FindnotconnectableHandler::class);
$router->post('/admin/findnotconnectable.php', \PU239\Http\Handlers\Admin\FindnotconnectableHandler::class);
$router->get('/admin/floodlimit.php', \PU239\Http\Handlers\Admin\FloodlimitHandler::class);
$router->post('/admin/floodlimit.php', \PU239\Http\Handlers\Admin\FloodlimitHandler::class);
$router->get('/admin/forum_config.php', \PU239\Http\Handlers\Admin\ForumConfigHandler::class);
$router->post('/admin/forum_config.php', \PU239\Http\Handlers\Admin\ForumConfigHandler::class);
$router->get('/admin/forum_manage.php', \PU239\Http\Handlers\Admin\ForumManageHandler::class);
$router->post('/admin/forum_manage.php', \PU239\Http\Handlers\Admin\ForumManageHandler::class);
$router->get('/admin/freeleech.php', \PU239\Http\Handlers\Admin\FreeleechHandler::class);
$router->post('/admin/freeleech.php', \PU239\Http\Handlers\Admin\FreeleechHandler::class);
$router->get('/admin/grouppm.php', \PU239\Http\Handlers\Admin\GrouppmHandler::class);
$router->post('/admin/grouppm.php', \PU239\Http\Handlers\Admin\GrouppmHandler::class);
$router->get('/admin/hit_and_run_settings.php', \PU239\Http\Handlers\Admin\HitAndRunSettingsHandler::class);
$router->post('/admin/hit_and_run_settings.php', \PU239\Http\Handlers\Admin\HitAndRunSettingsHandler::class);
$router->get('/admin/hnrwarn.php', \PU239\Http\Handlers\Admin\HnrwarnHandler::class);
$router->post('/admin/hnrwarn.php', \PU239\Http\Handlers\Admin\HnrwarnHandler::class);
$router->get('/admin/inactive.php', \PU239\Http\Handlers\Admin\InactiveHandler::class);
$router->post('/admin/inactive.php', \PU239\Http\Handlers\Admin\InactiveHandler::class);
$router->get('/admin/invite_tree.php', \PU239\Http\Handlers\Admin\InviteTreeHandler::class);
$router->post('/admin/invite_tree.php', \PU239\Http\Handlers\Admin\InviteTreeHandler::class);
$router->get('/admin/leechwarn.php', \PU239\Http\Handlers\Admin\LeechwarnHandler::class);
$router->post('/admin/leechwarn.php', \PU239\Http\Handlers\Admin\LeechwarnHandler::class);
$router->get('/admin/log_viewer.php', \PU239\Http\Handlers\Admin\LogViewerHandler::class);
$router->post('/admin/log_viewer.php', \PU239\Http\Handlers\Admin\LogViewerHandler::class);
$router->get('/admin/manage_images.php', \PU239\Http\Handlers\Admin\ManageImagesHandler::class);
$router->post('/admin/manage_images.php', \PU239\Http\Handlers\Admin\ManageImagesHandler::class);
$router->get('/admin/mass_bonus_for_members.php', \PU239\Http\Handlers\Admin\MassBonusForMembersHandler::class);
$router->post('/admin/mass_bonus_for_members.php', \PU239\Http\Handlers\Admin\MassBonusForMembersHandler::class);
$router->get('/admin/mega_search.php', \PU239\Http\Handlers\Admin\MegaSearchHandler::class);
$router->post('/admin/mega_search.php', \PU239\Http\Handlers\Admin\MegaSearchHandler::class);
$router->get('/admin/modded_torrents.php', \PU239\Http\Handlers\Admin\ModdedTorrentsHandler::class);
$router->post('/admin/modded_torrents.php', \PU239\Http\Handlers\Admin\ModdedTorrentsHandler::class);
$router->get('/admin/modtask.php', \PU239\Http\Handlers\Admin\ModtaskHandler::class);
$router->post('/admin/modtask.php', \PU239\Http\Handlers\Admin\ModtaskHandler::class);
$router->get('/admin/news.php', \PU239\Http\Handlers\Admin\NewsHandler::class);
$router->post('/admin/news.php', \PU239\Http\Handlers\Admin\NewsHandler::class);
$router->get('/admin/over_forums.php', \PU239\Http\Handlers\Admin\OverForumsHandler::class);
$router->post('/admin/over_forums.php', \PU239\Http\Handlers\Admin\OverForumsHandler::class);
$router->get('/admin/polls_manager.php', \PU239\Http\Handlers\Admin\PollsManagerHandler::class);
$router->post('/admin/polls_manager.php', \PU239\Http\Handlers\Admin\PollsManagerHandler::class);
$router->get('/admin/promo.php', \PU239\Http\Handlers\Admin\PromoHandler::class);
$router->post('/admin/promo.php', \PU239\Http\Handlers\Admin\PromoHandler::class);
$router->get('/admin/reputation_settings.php', \PU239\Http\Handlers\Admin\ReputationSettingsHandler::class);
$router->post('/admin/reputation_settings.php', \PU239\Http\Handlers\Admin\ReputationSettingsHandler::class);
$router->get('/admin/reset.php', \PU239\Http\Handlers\Admin\ResetHandler::class);
$router->post('/admin/reset.php', \PU239\Http\Handlers\Admin\ResetHandler::class);
$router->get('/admin/site_settings.php', \PU239\Http\Handlers\Admin\SiteSettingsHandler::class);
$router->post('/admin/site_settings.php', \PU239\Http\Handlers\Admin\SiteSettingsHandler::class);
$router->get('/admin/sysoplog.php', \PU239\Http\Handlers\Admin\SysoplogHandler::class);
$router->post('/admin/sysoplog.php', \PU239\Http\Handlers\Admin\SysoplogHandler::class);
$router->get('/admin/themes.php', \PU239\Http\Handlers\Admin\ThemesHandler::class);
$router->post('/admin/themes.php', \PU239\Http\Handlers\Admin\ThemesHandler::class);
$router->get('/admin/traceroute.php', \PU239\Http\Handlers\Admin\TracerouteHandler::class);
$router->post('/admin/traceroute.php', \PU239\Http\Handlers\Admin\TracerouteHandler::class);
$router->get('/admin/trivia_config.php', \PU239\Http\Handlers\Admin\TriviaConfigHandler::class);
$router->post('/admin/trivia_config.php', \PU239\Http\Handlers\Admin\TriviaConfigHandler::class);
$router->get('/admin/upgrade_database.php', \PU239\Http\Handlers\Admin\UpgradeDatabaseHandler::class);
$router->post('/admin/upgrade_database.php', \PU239\Http\Handlers\Admin\UpgradeDatabaseHandler::class);
$router->get('/admin/uploadapps.php', \PU239\Http\Handlers\Admin\UploadappsHandler::class);
$router->post('/admin/uploadapps.php', \PU239\Http\Handlers\Admin\UploadappsHandler::class);
$router->get('/admin/usersearch.php', \PU239\Http\Handlers\Admin\UsersearchHandler::class);
$router->post('/admin/usersearch.php', \PU239\Http\Handlers\Admin\UsersearchHandler::class);
$router->get('/admin/watched_users.php', \PU239\Http\Handlers\Admin\WatchedUsersHandler::class);
$router->post('/admin/watched_users.php', \PU239\Http\Handlers\Admin\WatchedUsersHandler::class);
$router->get('/ajax/autocomplete.php', \PU239\Http\Handlers\Public\Ajax\AutocompleteHandler::class);
$router->post('/ajax/autocomplete.php', \PU239\Http\Handlers\Public\Ajax\AutocompleteHandler::class);
$router->get('/ajax/bookmarks.php', \PU239\Http\Handlers\Public\Ajax\BookmarksHandler::class);
$router->post('/ajax/bookmarks.php', \PU239\Http\Handlers\Public\Ajax\BookmarksHandler::class);
$router->get('/ajax/checkport.php', \PU239\Http\Handlers\Public\Ajax\CheckportHandler::class);
$router->post('/ajax/checkport.php', \PU239\Http\Handlers\Public\Ajax\CheckportHandler::class);
$router->get('/ajax/checkports.php', \PU239\Http\Handlers\Public\Ajax\CheckportsHandler::class);
$router->post('/ajax/checkports.php', \PU239\Http\Handlers\Public\Ajax\CheckportsHandler::class);
$router->get('/ajax/cooker_notify.php', \PU239\Http\Handlers\Public\Ajax\CookerNotifyHandler::class);
$router->post('/ajax/cooker_notify.php', \PU239\Http\Handlers\Public\Ajax\CookerNotifyHandler::class);
$router->get('/ajax/descr_format.php', \PU239\Http\Handlers\Public\Ajax\DescrFormatHandler::class);
$router->post('/ajax/descr_format.php', \PU239\Http\Handlers\Public\Ajax\DescrFormatHandler::class);
$router->get('/ajax/ebook_lookup.php', \PU239\Http\Handlers\Public\Ajax\EbookLookupHandler::class);
$router->post('/ajax/ebook_lookup.php', \PU239\Http\Handlers\Public\Ajax\EbookLookupHandler::class);
$router->get('/ajax/imdb_lookup.php', \PU239\Http\Handlers\Public\Ajax\ImdbLookupHandler::class);
$router->post('/ajax/imdb_lookup.php', \PU239\Http\Handlers\Public\Ajax\ImdbLookupHandler::class);
$router->get('/ajax/isbn_lookup.php', \PU239\Http\Handlers\Public\Ajax\IsbnLookupHandler::class);
$router->post('/ajax/isbn_lookup.php', \PU239\Http\Handlers\Public\Ajax\IsbnLookupHandler::class);
$router->get('/ajax/like.php', \PU239\Http\Handlers\Public\Ajax\LikeHandler::class);
$router->post('/ajax/like.php', \PU239\Http\Handlers\Public\Ajax\LikeHandler::class);
$router->get('/ajax/member_input.php', \PU239\Http\Handlers\Public\Ajax\MemberInputHandler::class);
$router->post('/ajax/member_input.php', \PU239\Http\Handlers\Public\Ajax\MemberInputHandler::class);
$router->get('/ajax/offer_notify.php', \PU239\Http\Handlers\Public\Ajax\OfferNotifyHandler::class);
$router->post('/ajax/offer_notify.php', \PU239\Http\Handlers\Public\Ajax\OfferNotifyHandler::class);
$router->get('/ajax/offer_status.php', \PU239\Http\Handlers\Public\Ajax\OfferStatusHandler::class);
$router->post('/ajax/offer_status.php', \PU239\Http\Handlers\Public\Ajax\OfferStatusHandler::class);
$router->get('/ajax/offer_vote.php', \PU239\Http\Handlers\Public\Ajax\OfferVoteHandler::class);
$router->post('/ajax/offer_vote.php', \PU239\Http\Handlers\Public\Ajax\OfferVoteHandler::class);
$router->get('/ajax/rating.php', \PU239\Http\Handlers\Public\Ajax\RatingHandler::class);
$router->post('/ajax/rating.php', \PU239\Http\Handlers\Public\Ajax\RatingHandler::class);
$router->get('/ajax/request_notify.php', \PU239\Http\Handlers\Public\Ajax\RequestNotifyHandler::class);
$router->post('/ajax/request_notify.php', \PU239\Http\Handlers\Public\Ajax\RequestNotifyHandler::class);
$router->get('/ajax/request_vote.php', \PU239\Http\Handlers\Public\Ajax\RequestVoteHandler::class);
$router->post('/ajax/request_vote.php', \PU239\Http\Handlers\Public\Ajax\RequestVoteHandler::class);
$router->get('/ajax/show_in_navbar.php', \PU239\Http\Handlers\Public\Ajax\ShowInNavbarHandler::class);
$router->post('/ajax/show_in_navbar.php', \PU239\Http\Handlers\Public\Ajax\ShowInNavbarHandler::class);
$router->get('/ajax/staff_picks.php', \PU239\Http\Handlers\Public\Ajax\StaffPicksHandler::class);
$router->post('/ajax/staff_picks.php', \PU239\Http\Handlers\Public\Ajax\StaffPicksHandler::class);
$router->get('/ajax/take_upload.php', \PU239\Http\Handlers\Public\Ajax\TakeUploadHandler::class);
$router->post('/ajax/take_upload.php', \PU239\Http\Handlers\Public\Ajax\TakeUploadHandler::class);
$router->get('/ajax/take_url_upload.php', \PU239\Http\Handlers\Public\Ajax\TakeUrlUploadHandler::class);
$router->post('/ajax/take_url_upload.php', \PU239\Http\Handlers\Public\Ajax\TakeUrlUploadHandler::class);
$router->get('/ajax/thanks.php', \PU239\Http\Handlers\Public\Ajax\ThanksHandler::class);
$router->post('/ajax/thanks.php', \PU239\Http\Handlers\Public\Ajax\ThanksHandler::class);
$router->get('/ajax/torrents_lookup.php', \PU239\Http\Handlers\Public\Ajax\TorrentsLookupHandler::class);
$router->post('/ajax/torrents_lookup.php', \PU239\Http\Handlers\Public\Ajax\TorrentsLookupHandler::class);
$router->get('/ajax/trivia_answers.php', \PU239\Http\Handlers\Public\Ajax\TriviaAnswersHandler::class);
$router->post('/ajax/trivia_answers.php', \PU239\Http\Handlers\Public\Ajax\TriviaAnswersHandler::class);
$router->get('/ajax/tvmaze_lookup.php', \PU239\Http\Handlers\Public\Ajax\TvmazeLookupHandler::class);
$router->post('/ajax/tvmaze_lookup.php', \PU239\Http\Handlers\Public\Ajax\TvmazeLookupHandler::class);
$router->get('/ajax/usersearch.php', \PU239\Http\Handlers\Public\Ajax\UsersearchHandler::class);
$router->post('/ajax/usersearch.php', \PU239\Http\Handlers\Public\Ajax\UsersearchHandler::class);
$router->get('/index.legacy.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/index.legacy.php']);
$router->post('/index.legacy.php', LegacyProxyHandler::class, ['legacy' => __DIR__ . '/index.legacy.php']);
$router->get('/search.php', \PU239\Http\Handlers\Public\SearchHandler::class);
$router->post('/search.php', \PU239\Http\Handlers\Public\SearchHandler::class);
$router->get('/signup.php', \PU239\Http\Handlers\Public\SignupHandler::class);
$router->post('/signup.php', \PU239\Http\Handlers\Public\SignupHandler::class);
$router->get('/subtitles.php', \PU239\Http\Handlers\Public\SubtitlesHandler::class);
$router->post('/subtitles.php', \PU239\Http\Handlers\Public\SubtitlesHandler::class);
$router->get('/tags.php', \PU239\Http\Handlers\Public\TagsHandler::class);
$router->post('/tags.php', \PU239\Http\Handlers\Public\TagsHandler::class);
$router->get('/upcoming.php', \PU239\Http\Handlers\Public\UpcomingHandler::class);
$router->post('/upcoming.php', \PU239\Http\Handlers\Public\UpcomingHandler::class);
$router->get('/uploadapp.php', \PU239\Http\Handlers\Public\UploadappHandler::class);
$router->post('/uploadapp.php', \PU239\Http\Handlers\Public\UploadappHandler::class);
$router->get('/user_blocks.php', \PU239\Http\Handlers\Public\UserBlocksHandler::class);
$router->post('/user_blocks.php', \PU239\Http\Handlers\Public\UserBlocksHandler::class);

// Legacy HTTP front controller marker

// Admin/staff (with AuthZGate metadata)
$router->get('/admin/namechanger.php', \PU239\Http\Handlers\Admin\NamechangerHandler::class, ['authz' => new AuthZGate('admin')]);
$router->get('/admin/reports.php', \PU239\Http\Handlers\Admin\ReportsHandler::class, ['authz' => new AuthZGate('admin')]);
$router->get('/admin/warn.php', \PU239\Http\Handlers\Admin\WarnHandler::class, ['authz' => new AuthZGate('admin')]);
$router->get('/admin/class_promo.php', \PU239\Http\Handlers\Admin\ClassPromoHandler::class, ['authz' => new AuthZGate('admin')]);
$router->get('/admin/sitelog.php', \PU239\Http\Handlers\Admin\SitelogHandler::class, ['authz' => new AuthZGate('admin')]);
$router->get('/admin/comments.php', \PU239\Http\Handlers\Admin\CommentsHandler::class, ['authz' => new AuthZGate('admin')]);
$router->get('/admin/reputation_ad.php', \PU239\Http\Handlers\Admin\ReputationAdHandler::class, ['authz' => new AuthZGate('admin')]);
$router->get('/admin/shit_list.php', \PU239\Http\Handlers\Admin\ShitListHandler::class, ['authz' => new AuthZGate('admin')]);
$router->get('/admin/system_view.php', \PU239\Http\Handlers\Admin\SystemViewHandler::class, ['authz' => new AuthZGate('admin')]);

$router->get('/staffpanel.php', \PU239\Http\Handlers\Staffpanel\IndexHandler::class, ['authz' => new AuthZGate(['any' => ['staff', 'admin']])]);
$router->get('/staffpanel/index.php', \PU239\Http\Handlers\Staffpanel\IndexHandler::class, ['authz' => new AuthZGate(['any' => ['staff', ' admin']])]);

    $router->post('/bitbucket.php', \PU239\Http\Handlers\PublicSite\BitbucketHandler::class);
    $router->post('/browse.php', \PU239\Http\Handlers\PublicSite\BrowseHandler::class);
    $router->post('/rss.php', \PU239\Http\Handlers\PublicSite\RssHandler::class);
    $router->get('/bootstrap_web.php', \PU239\Http\Handlers\Public\BootstrapWebHandler::class);
    $router->post('/getrss.php', \PU239\Http\Handlers\PublicSite\GetrssHandler::class);
    $router->post('/forums.php', \PU239\Http\Handlers\PublicSite\ForumsHandler::class);
    $router->post('/bot_triggers.php', \PU239\Http\Handlers\PublicSite\BotTriggersHandler::class);
    $router->post('/hnrs.php', \PU239\Http\Handlers\PublicSite\HnrsHandler::class);
    $router->get('/sharemarks.php', \PU239\Http\Handlers\Public\SharemarksHandler::class);
    $router->get('/snatches.php', \PU239\Http\Handlers\Public\SnatchesHandler::class);
    $router->post('/blackjack.php', \PU239\Http\Handlers\PublicSite\BlackjackHandler::class);
    $router->get('/scrape.php', \PU239\Http\Handlers\Public\ScrapeHandler::class);
    $router->get('/staff.php', \PU239\Http\Handlers\Public\StaffHandler::class);
    $router->post('/casino.php', \PU239\Http\Handlers\PublicSite\CasinoHandler::class);
    $router->get('/setclass.php', \PU239\Http\Handlers\Public\SetclassHandler::class);
    $router->get('/announce.php', \PU239\Http\Handlers\Public\AnnounceHandler::class);
    $router->get('/upload.php', \PU239\Http\Handlers\Public\UploadHandler::class);
    $router->get('/ajax/trivia_lookup.php', \PU239\Http\Handlers\Public\Ajax\TriviaLookupHandler::class);
    $router->get('/ajax/ajax_tooltips.php', \PU239\Http\Handlers\Public\Ajax\AjaxTooltipsHandler::class);
    $router->get('/ajax/emailcheck.php', \PU239\Http\Handlers\Public\Ajax\EmailcheckHandler::class);
    $router->get('/ajax/namecheck.php', \PU239\Http\Handlers\Public\Ajax\NamecheckHandler::class);
    $router->get('/ajax/view_sql.php', \PU239\Http\Handlers\Public\Ajax\ViewSqlHandler::class);
    $router->get('/admin/memcache.php', \PU239\Http\Handlers\Admin\MemcacheHandler::class);
    $router->get('/admin/banclient.php', \PU239\Http\Handlers\Admin\BanclientHandler::class);
    $router->get('/admin/user_hits.php', \PU239\Http\Handlers\Admin\UserHitsHandler::class);
    $router->get('/admin/allagents.php', \PU239\Http\Handlers\Admin\AllagentsHandler::class);
    $router->get('/admin/uploader_info.php', \PU239\Http\Handlers\Admin\UploaderInfoHandler::class);
    $router->get('/admin/doubleusers.php', \PU239\Http\Handlers\Admin\DoubleusersHandler::class);
    $router->get('/admin/op.php', \PU239\Http\Handlers\Admin\OpHandler::class);
    $router->get('/admin/view_peers.php', \PU239\Http\Handlers\Admin\ViewPeersHandler::class);
    $router->get('/admin/donations.php', \PU239\Http\Handlers\Admin\DonationsHandler::class);
    $router->get('/admin/changelog.php', \PU239\Http\Handlers\Admin\ChangelogHandler::class);
    $router->get('/admin/referrers.php', \PU239\Http\Handlers\Admin\ReferrersHandler::class);
    $router->get('/admin/stats_extra.php', \PU239\Http\Handlers\Admin\StatsExtraHandler::class);
    $router->get('/admin/stats.php', \PU239\Http\Handlers\Admin\StatsHandler::class);
    $router->get('/admin/load.php', \PU239\Http\Handlers\Admin\LoadHandler::class);
    $router->get('/admin/mysql_overview.php', \PU239\Http\Handlers\Admin\MysqlOverviewHandler::class);
    $router->get('/admin/ipsearch.php', \PU239\Http\Handlers\Admin\IpsearchHandler::class);
    $router->get('/admin/snatched_torrents.php', \PU239\Http\Handlers\Admin\SnatchedTorrentsHandler::class);
    $router->get('/admin/hit_and_run.php', \PU239\Http\Handlers\Admin\HitAndRunHandler::class);
    $router->get('/admin/mysql_stats.php', \PU239\Http\Handlers\Admin\MysqlStatsHandler::class);
    $router->get('/admin/freeusers.php', \PU239\Http\Handlers\Admin\FreeusersHandler::class);
    $router->get('/admin/iphistory.php', \PU239\Http\Handlers\Admin\IphistoryHandler::class);
    $router->get('/admin/todo.php', \PU239\Http\Handlers\Admin\TodoHandler::class);
    $router->get('/admin/goaccess.php', \PU239\Http\Handlers\Admin\GoaccessHandler::class);
    $router->get('/admin/ipcheck.php', \PU239\Http\Handlers\Admin\IpcheckHandler::class);
    $router->get('/admin/flush.php', \PU239\Http\Handlers\Admin\FlushHandler::class);
    $router->post('/staffpanel/index.php', \PU239\Http\Handlers\Staffpanel\IndexHandler::class, ['authz' => new AuthZGate(['any' => ['staff', 'admin']])]);
    $router->get('/staffpanel', \PU239\Http\Handlers\Staffpanel\IndexHandler::class, ['authz' => new AuthZGate(['any' => ['staff', 'admin']])]);
$pipeline->handle($router);

// Legacy HTTP front controller marker
