name: Repo Sanity

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Check repo sanitation
        run: php tools/repo_sanity.php
