name: Run Fixers (short-tags & terminate)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-fixers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Run short tag fixer
        run: php tools/fix_short_open_tags.php
      - name: Run terminate fixer
        run: php tools/fix_terminate_calls.php
      - name: Commit & push changes (if any)
        run: |
          set -e
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: fix short tags and terminate() in AJAXChat.php & rss.php"
            git push
          else
            echo "No changes to commit."
          fi
