name: Static Guard

on:
  push:
  pull_request:
  workflow_dispatch:  # ← gør det muligt at starte manuelt fra Actions

permissions:
  contents: read

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_mysql
      - name: Run static guard
        run: php tools/static_guard.php
