name: Static Guard (strict)

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Run static guard (strict rules)
        env:
          GUARD_MODE: fail
          GUARD_EXCLUDE: admin/adminer.php,tools/static_guard.php
          GUARD_FAIL_ON: merge_conflict_marker,short_open_tag,eval_usage,terminate_calls,debug_calls,deprecated_mysql
        run: php tools/static_guard.php
